
wa_verify_token = "Sana"
phone_number_id = "209325405605976"
access_token = "EAARxAciB8DkBO6UlzRKMARpFeCosVfuQclOcgkQWZANaGbm0NVF7O4oSP1mh0O0siNmDY62yuKMvlWLU75poYachLFWLxOZAocv9j4FNBC512VxQkWzvdZAIqIh2tdB6ZBsS7BEI4Y9UyklVNveRqqsNsXyJuvzuBuiVxfaZBZAU0Oen8hhy7GBn1zbXznVLRPhQjL3eXeUV0zZAUgLQo2dFQ8FoxsZD"
wa_base_url = "https://graph.facebook.com/v19.0/" + phone_number_id
wa_request_url = wa_base_url + "/messages"
wa_media_url = wa_base_url + "/media"
wa_local_files_repo = r"C:\Users\aashraf\Desktop\Test_Folder\WA_Media"


#xcally_open_channel_id = 5

xcally_channel_key = "Sana"
xcally_api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjI1MzQwMjMwMDgwMCwibm9uY2UiOiIyN2E4OTI4MDdjYzY5NDBiODYxN2Y3NTZkYjFlNGY5OSIsInN1YiI6MSwiaXNzIjoiY2MyY2RmMTktMjYzMi05N2FhLWI2Y2EtYWJiMDczMjJhZWY2IiwiYXVkIjoiMzM2MmNlYTAxNTg0YWY2Yjk0ZDk0YzgwZTA3YTBjODZiYTkzODU2MDk4OWIwYzgwN2UzYmY0Yjk1Nzk2YTBjZTRiMWQ4ODBkMjRmZWYwMTY0MDY3MzhkZGU2YzQzZDJjMjU2ZWJiZTgwZDMxMDIzODkyNjkwMTI1N2VjYWJjZjYiLCIzMzYyY2VhMDE1ODRhZjZiOTRkOTRjODBlMDdhMGM4NmJhOTM4NTYwOTg5YjBjODA3ZTNiZjRiOTU3OTZhMGNlNGIxZDg4MGQyNGZlZjAxNjQwNjczOGRkZTZjNDNkMmMyNTZlYmJlODBkMzEwMjM4OTI2OTAxMjU3ZWNhYmNmNiI6bnVsbH0.u7N-axzujAQTbs-5VwBUmoQguQx7IveKETdkq9Gbor4"
xcally_open_channel_id = "5"
xcally_base_url = "https://xcally.sanasofteg.com/api"
xcally_create_msg_url = xcally_base_url+"/openchannel/accounts/"+xcally_open_channel_id+"/notify?apikey="+xcally_api_key
xcally_local_files_repo = r"C:\Users\aashraf\Desktop\Test_Folder\XCally_Attachments"
