
wa_verify_token = "Sana"
phone_number_id = "209325405605976"
access_token = "EAARxAciB8DkBO0mksIp4KAcfiKnBiZCGA1AEZASdTZAG6dLvuC0J2kurPR6GT270BYqJwii3bPweNoLsdCjk2S6QxZBmZB9ZC71CjP0bjLmYwABWDozTqbyzziKzvU81NkIjek2wrO9r8bS3rla8KAi3zSqdFaGx0oKCL5ih6EEulsb7Y8gmF5ZAe7sd7YvuoIUMXpnPtwYsH0MLJImuyuSkh9JUwsZD"
wa_base_url = "https://graph.facebook.com/v19.0/" + phone_number_id
wa_request_url = wa_base_url + "/messages"
wa_media_url = wa_base_url + "/media"
wa_local_files_repo = r"C:\Users\aashraf\Desktop\Test_Folder\WA_Media"


xcally_channel_key = "Sana"
xcally_api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjI1MzQwMjMwMDgwMCwibm9uY2UiOiIyN2E4OTI4MDdjYzY5NDBiODYxN2Y3NTZkYjFlNGY5OSIsInN1YiI6MSwiaXNzIjoiYzAyOWMwMzEtMDQwZC0yODVkLTkyNWMtZTYzZWUyZGQyOTQ0IiwiYXVkIjoiMzM2MmNlYTAxNTg0YWY2Yjk0ZDk0YzgwZTA3YTBjODZiYTkzODU2MDk4OWIwYzgwN2UzYmY0Yjk1Nzk2YTBjZTRiMWQ4ODBkMjRmZWYwMTY0MDY3MzhkZGU2YzQzZDJjMjU2ZWJiZTgwZDMxMDIzODkyNjkwMTI1N2VjYWJjZjYiLCIzMzYyY2VhMDE1ODRhZjZiOTRkOTRjODBlMDdhMGM4NmJhOTM4NTYwOTg5YjBjODA3ZTNiZjRiOTU3OTZhMGNlNGIxZDg4MGQyNGZlZjAxNjQwNjczOGRkZTZjNDNkMmMyNTZlYmJlODBkMzEwMjM4OTI2OTAxMjU3ZWNhYmNmNiI6bnVsbH0.No6IKCmVfgMrWtv-jgK0jfUSLkVuQ822McqMxrbP6EU"
xcally_open_channel_id = "5"
xcally_base_url = "https://xcally.sanasofteg.com/api"
xcally_create_msg_url = xcally_base_url+"/openchannel/accounts/"+xcally_open_channel_id+"/notify?apikey="+xcally_api_key
xcally_local_files_repo = r"C:\Users\aashraf\Desktop\Test_Folder\XCally_Attachments"
